wiki/wiki/encyclopedia/urls.py
from django.urls import path, include

from . import views

app_name ="wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("links", views.links, name="links"),
    path("add_page", views.newPage, name="add_page"),
    path("wiki/edit/<str:title>", views.edit, name="edit"),
    path("random", views.random, name="random"),
   
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django import forms
from django.urls import reverse
import markdown2
from random import randint
from . import util


class NewForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))
    
class AddPageForm(forms.Form):
    title = forms.CharField(label="Name of web page")
    textArea = forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'cols':5}))

# It handles search bar of wiki homepage. If request is "post", it ultimately redirects
# to "link" path where it will be rendered a page with all the results from the search. 

def index(request):

    if "entries" not in request.session:
        request.session["entries"] = []

    if request.method == "POST":
        request.session["entries"].clear()
        form = NewForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search"]
            list = [x.lower() for x in util.list_entries() if search.lower() in x.lower()]
            if len(list) != 0:
                request.session["entries"] += list
                #page = util.get_entry("search")
                return HttpResponseRedirect(reverse("wiki:links"))
               
            else:
                return render(request,"encyclopedia/index.html")
        else:
            return render(request,"encyclopedia/index.html",{
                "form":form
            })
            
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries() , "form": NewForm()
    })

# It is responsible to convert markdown file format into html when user access wiki page

def entry(request,entry):
    
    if util.get_entry(entry) == None:
        return HttpResponseRedirect(reverse("wiki:index"))
   
    return render(request,"encyclopedia/pages.html",{
        "entry": markdown2.Markdown().convert(util.get_entry(entry)),
        "title": entry  
    })

def links(request):
    return render(request,"encyclopedia/search.html",{
                    "entry": request.session["entries"]
                   })


# It is path dedicated to creating a new wiki page when an user clicks "create new page"
# from homepage.

def newPage(request):
    if request.method == "POST":
        form = AddPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            textArea = form.cleaned_data["textArea"]

            if title in util.list_entries():
                return HttpResponse("Error, multiple files with same name") 
            util.save_entry(title,textArea)
            #request.session["entries"] += [title]
            return HttpResponseRedirect(reverse('wiki:entry', args=(title,)))

        return render(request,"encyclopedia/newPage.html",{
            "form": form})
    return render(request,"encyclopedia/newPage.html", {
        "form": AddPageForm()})

# Below every page, an user can press a link that allows them to edit it. It sets by default
# a textarea value that is the previous page's content and as hidden value the name of the page.
 
def edit(request,title):
    if request.method == "POST":
        form = AddPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            textArea = form.cleaned_data["textArea"]
            util.save_entry(title,textArea)
            return HttpResponseRedirect(reverse("wiki:entry",args=(title,)))
        else:
            return render(request,"encyclopedia/edit.html",{
                "form":form, "title":title, 
            })
    new_form = AddPageForm()
    new_form.fields["textArea"].initial = util.get_entry(title)
    new_form.fields["textArea"].label = ""
    new_form.fields["title"].initial = title
    new_form.fields["title"].widget = new_form.fields["title"].hidden_widget()
      
    return render(request,"encyclopedia/edit.html",{
        "title":title,
        "form":new_form 
    })

# Returns random existing wiki page.

def random(request):
    length = util.list_entries()
    range = len(length)
    rand_index = randint(0,range)
    return HttpResponseRedirect(reverse("wiki:entry",args=(length[rand_index],)))




    

wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

<h1  id="h1">Edit text</h1>
    <form action="{% url 'wiki:edit' title %}" method="post">
            {% csrf_token %}
                {{ form }}
        <br>
            <button type="submit" id="button" > Save </button>
    </form>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block form %}
<form action= "{% url 'wiki:index' %}"   method = "post">
    {% csrf_token %}
    {{ form.search }}
    
</form>

{% endblock %}


{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>
    
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>      
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
               {% block form %} {% endblock %}
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}"> Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1 id="h1"> Add a new page</h1>
    <form action="{% url 'wiki:add_page' %}" method="post">
        {% csrf_token %}
            {{ form }}
        <br>
        <button type="submit" id="button" > Save </button>
    </form>     
        
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/pages.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block body %}

    {{ entry|safe }}
    <br>
    
    <a href="{% url 'wiki:edit' title %}">Edit</a> 
   

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    <h1> Pages</h1>
    <ul>
        
        {% for entry in entry %}
        
            <li><a href ="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
       
        {% endfor %}
        
    </ul>
    
{% endblock %}